### ISSUE TITLE
[FIX] CategorySelectView 집보기 시간 수정하기

### ISSUE THREAD

**Issue by lemonisgreen** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#119]
## 🚩 TO-DO
- [ ] 카테고리별 집보기 시간 측정
- [ ] 카테고리별 집보기 시간 수정
- [ ] SettingView에서도 시간 수정하기
