### ISSUE TITLE
[Setting] 체크리스트 데이터 구조 세팅 및 추가

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#23]
## 🚩 TO-DO
- [ ] 체크리스트 데이터 구조 짜기
- [ ] 체크리스트 데이터 추가하기
- [ ] 스위프트 데이터 추상화?
