### ISSUE TITLE
[Design] MainView UI 구현

### ISSUE THREAD

**Issue by lemonisgreen** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#30]
## 🚩 TO-DO
- [ ] 집집사의 팁 자동전환 구현
- [ ] 집 보러가기 버튼과 내가 본 집 버튼 만들기
- [ ] 최근 본 집 데이터 있/없에 따라 바뀌게 만들기 
- [ ] 드뮤어하게 코딩하기
