### ISSUE TITLE
[Chore] 컬러 시스템, 타이포 시스템 추가

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#34]
## 🚩 TO-DO
- [ ] 컬러 에셋에 추가
- [ ] 컬러 extension에 용도에 맞게 네이밍 하여 추가
- [ ] 타이포 시스템 추가
