### ISSUE TITLE
[Design] RoomScanView UI 구현

### ISSUE THREAD

**Issue by WooFeather** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#40]
## 🚩 TO-DO
- [ ] RoomScanView 색상 및 폰트 적용
- [ ] RoomScanView에서 모델이 제대로 스캔되지 않았을 때 분기처리
- [ ] RoomScanInfoView UI 구현
- [ ] UnsupportedDeviceView UI 구현
