### ISSUE TITLE
[Design] SettingView 구현

### ISSUE THREAD

**Issue by lemonisgreen** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#51]
## 🚩 TO-DO
- [ ] 선택한 카테고리가 뜨게 해야 함.
- [ ] 카테고리 수정할 수 있게 해야 함.
- [ ] 카테고리 셀렉트뷰에서 버튼 선택 해제할 때 기본 문구가 뜨게 하기.
